-- MySQL Script generated by MySQL Workbench
-- 08/14/17 21:48:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop` ;

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`t_Cmd_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_Cmd_Type` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_Cmd_Type` (
  `id` VARCHAR(36) NOT NULL,
  `parent_id` VARCHAR(36) NULL COMMENT '商品类型父Id',
  `type_name` VARCHAR(100) NULL COMMENT '商品类别名称',
  `create_tsp` DATETIME default current_timestamp  COMMENT '创建时间戳',
  `change_tsp` DATETIME default current_timestamp COMMENT '更改时间戳',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`t_Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_Brand` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_Brand` (
  `id` VARCHAR(36) NOT NULL COMMENT '品牌主键',
  `brand_name` VARCHAR(100) NULL COMMENT '品牌名称',
  `desc` VARCHAR(1000) NULL COMMENT '品牌描述',
  `create_tsp` DATETIME default current_timestamp,
  `change_tsp` DATETIME default current_timestamp ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`t_Commodity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_Commodity` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_Commodity` (
  `id` VARCHAR(36) NOT NULL COMMENT '主键',
  `cmd_name` VARCHAR(100) NULL COMMENT '商品名称',
  `cmd_desc` VARCHAR(1000) NULL COMMENT '商品描述',
  `cmd_price` VARCHAR(32) NULL COMMENT '商品价格',
  `create_tsp` DATETIME default current_timestamp COMMENT '创建时间',
  `change_tsp` DATETIME default current_timestamp COMMENT '更改时间',
  `t_Cmd_Type_id1` VARCHAR(36) NOT NULL,
  `t_Brand_id1` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_t_Commodity_t_Cmd_Type1`
    FOREIGN KEY (`t_Cmd_Type_id1`)
    REFERENCES `shop`.`t_Cmd_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_Commodity_t_Brand1`
    FOREIGN KEY (`t_Brand_id1`)
    REFERENCES `shop`.`t_Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_t_Commodity_t_Cmd_Type1_idx` ON `shop`.`t_Commodity` (`t_Cmd_Type_id1` ASC);

CREATE INDEX `fk_t_Commodity_t_Brand1_idx` ON `shop`.`t_Commodity` (`t_Brand_id1` ASC);


-- -----------------------------------------------------
-- Table `shop`.`t_Cmd_Pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_Cmd_Pic` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_Cmd_Pic` (
  `id` VARCHAR(36) NOT NULL COMMENT '商品图片表主键',
  `pic_url` VARCHAR(255) NOT NULL COMMENT '图片存放路径',
  `show_as` VARCHAR(2) NULL COMMENT '图片展示类型',
  `pic_index` VARCHAR(3) NULL COMMENT '图片顺序',
  `change_tsp` DATETIME default current_timestamp,
  `create_tsp` DATETIME default current_timestamp,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`t_Commodity_has_t_Cmd_Pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_Commodity_has_t_Cmd_Pic` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_Commodity_has_t_Cmd_Pic` (
  `t_Commodity_id` VARCHAR(36) NOT NULL COMMENT '商品id',
  `t_Cmd_Pic_id` VARCHAR(36) NOT NULL COMMENT '商品图片id',
  PRIMARY KEY (`t_Commodity_id`, `t_Cmd_Pic_id`),
  CONSTRAINT `fk_t_Commodity_has_t_Cmd_Pic_t_Commodity`
    FOREIGN KEY (`t_Commodity_id`)
    REFERENCES `shop`.`t_Commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_Commodity_has_t_Cmd_Pic_t_Cmd_Pic1`
    FOREIGN KEY (`t_Cmd_Pic_id`)
    REFERENCES `shop`.`t_Cmd_Pic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_t_Commodity_has_t_Cmd_Pic_t_Cmd_Pic1_idx` ON `shop`.`t_Commodity_has_t_Cmd_Pic` (`t_Cmd_Pic_id` ASC);

CREATE INDEX `fk_t_Commodity_has_t_Cmd_Pic_t_Commodity_idx` ON `shop`.`t_Commodity_has_t_Cmd_Pic` (`t_Commodity_id` ASC);


-- -----------------------------------------------------
-- Table `shop`.`t_CmdParam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_CmdParam` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_CmdParam` (
  `id` VARCHAR(36) NOT NULL COMMENT '主键',
  `cmd_key` VARCHAR(36) NULL COMMENT '商品属性键',
  `cmd_value` VARCHAR(100) NULL COMMENT '商品属性值',
  `create_tsp` DATETIME default current_timestamp  COMMENT '创建时间戳',
  `change_tsp` DATETIME default current_timestamp  COMMENT '更改时间戳',
  `t_Commodity_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_t_CmdParam_t_Commodity1`
    FOREIGN KEY (`t_Commodity_id`)
    REFERENCES `shop`.`t_Commodity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_t_CmdParam_t_Commodity1_idx` ON `shop`.`t_CmdParam` (`t_Commodity_id` ASC);


-- -----------------------------------------------------
-- Table `shop`.`t_Brand_has_t_Cmd_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`t_Brand_has_t_Cmd_Type` ;

CREATE TABLE IF NOT EXISTS `shop`.`t_Brand_has_t_Cmd_Type` (
  `t_Brand_id` VARCHAR(36) NOT NULL,
  `t_Cmd_Type_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`t_Brand_id`, `t_Cmd_Type_id`),
  CONSTRAINT `fk_t_Brand_has_t_Cmd_Type_t_Brand1`
    FOREIGN KEY (`t_Brand_id`)
    REFERENCES `shop`.`t_Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_Brand_has_t_Cmd_Type_t_Cmd_Type1`
    FOREIGN KEY (`t_Cmd_Type_id`)
    REFERENCES `shop`.`t_Cmd_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_t_Brand_has_t_Cmd_Type_t_Cmd_Type1_idx` ON `shop`.`t_Brand_has_t_Cmd_Type` (`t_Cmd_Type_id` ASC);

CREATE INDEX `fk_t_Brand_has_t_Cmd_Type_t_Brand1_idx` ON `shop`.`t_Brand_has_t_Cmd_Type` (`t_Brand_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
